"""Tests for the KML generator and ATOC branding."""

from pathlib import Path

from opt_refactor.generator import generate_styled_kml, _sanitise_text
from opt_refactor.parser import parse_kml_file

SAMPLE_DIR = Path(__file__).parent / "sample_data"


def _load_sample_features():
    return parse_kml_file(str(SAMPLE_DIR / "overpass_sample.kml"))


def test_generate_produces_valid_kml():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    assert '<?xml version' in kml_str
    assert 'kml' in kml_str


def test_atoc_branding_present():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    assert "ATOC" in kml_str


def test_overpass_references_stripped():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    lower = kml_str.lower()
    assert "overpass" not in lower
    assert "osmtogeojson" not in lower


def test_folders_created_by_default():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    assert "Folder" in kml_str


def test_no_folders_option():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features, use_folders=False)
    assert "Folder" not in kml_str


def test_styles_applied():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    assert "LineStyle" in kml_str
    assert "color" in kml_str.lower()


def test_sanitise_text():
    assert _sanitise_text("Overpass Turbo Export") == "Export"
    assert _sanitise_text("My Map") == "My Map"
    assert _sanitise_text("Exported from Overpass Turbo") == ""
    assert _sanitise_text("Generated by overpass-api data") == "data"


def test_point_features_get_icons():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    assert "IconStyle" in kml_str


def test_polygon_features_get_fill():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    assert "PolyStyle" in kml_str


def test_custom_document_name():
    features = _load_sample_features()
    kml_str = generate_styled_kml(features, document_name="My Custom Map")
    assert "My Custom Map" in kml_str


def test_geometry_preserved():
    """Verify that coordinate data makes it through to the output."""
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    # Main Street coordinates should be in the output
    assert "-73.9857,40.7484" in kml_str


def test_description_contains_tags():
    """Verify OSM tags are rendered in description balloons."""
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    # The pizza restaurant should have cuisine=pizza in its description
    assert "cuisine" in kml_str
    assert "pizza" in kml_str


def test_internal_tags_excluded_from_description():
    """@id and source tags should not appear in descriptions."""
    features = _load_sample_features()
    kml_str = generate_styled_kml(features)
    assert "@id" not in kml_str
